package org.openremote.agent.protocol.twitch;

public enum TwitchApiCommand {
    GET_USER_INFO,
    POST_CREATE_CLIP,
    SUB_CHAT_MESSAGES,
    SUB_USER_FOLLOW,
    SUB_USER_SUBSCRIBE,
    SUB_USER_CHEER,
    SUB_USER_BAN,
    SUB_USER_RAID,
    SUB_CHANNELPOINTS_CREATED,
    SUB_CHANNELPOINTS_REDEEMED,
    SUB_HYPETRAIN_APPROACHING,
    SUB_HYPETRAIN_START,
    SUB_HYPETRAIN_LEVELUP,
    SUB_HYPETRAIN_END
}
